name: Build and release binaries

on:
  push:
    branches: [master]
    tags: [stable]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  REFNAME: ${{ github.ref_name == 'master' && 'dev' || github.ref_name }}

jobs:
  release:
    name: Release  ${{ github.ref_name == 'master' && 'dev' || github.ref_name }} binaries for ${{ matrix.os.name }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    strategy:
      matrix:
        os:
          - name: WinXP
            mingw: 32
          - name: Win64
            mingw: 64
    env:
      OUTFILE: dwarfpaper-${{ matrix.os.name }}-${{ github.ref_name == 'master' && 'dev' || github.ref_name }}.exe
      MINGW_ARCH: ${{ matrix.os.mingw == 32 && 'i686' || 'x86_64' }}
      MINGW_SHIT: >-
        -D CMAKE_C_COMPILER=${MINGW_ARCH}-w64-mingw32-gcc
        -D CMAKE_CXX_COMPILER=${MINGW_ARCH}-w64-mingw32-g++
        -D CMAKE_RC_COMPILER=${MINGW_ARCH}-w64-mingw32-windres
        -D CMAKE_SYSTEM_NAME=Windows
        -D CMAKE_FIND_ROOT_PATH=/usr/${MINGW_ARCH}-w64-mingw32
        -D CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER
        -D CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
        -D CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install --yes \
            libgl1-mesa-dev python3-jinja2 \
            libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev
      - name: Install MinGW
        if: matrix.os.mingw
        uses: egor-tensin/setup-mingw@v2.2.0
        with:
          platform: ${{ matrix.os.mingw == 32 && 'x86' || 'x64' }}
          cc: 0
      - name: Cache dependency sources
        uses: actions/cache@v4
        with:
          path: build/_deps/*-src
          key: cmake-deps-src-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: cmake-deps-src-
      - name: Cache dependency build objects
        uses: actions/cache@v4
        with:
          path: |
            build/_deps/*-build
            build/_deps/*-subbuild
          key: cmake-deps-obj-${{ matrix.os.name }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: cmake-deps-obj-${{ matrix.os.name }}-
      - name: Configure
        run: cmake -G Ninja -S . -B build -D CMAKE_BUILD_TYPE=Release $MINGW_SHIT
      - name: Build
        run: cmake --build build --target dwarfpaper
      - name: Rename binary
        run: cp build/dwarfpaper.exe $OUTFILE
      - name: Release ${{ env.REFNAME }} build for ${{ matrix.os.name }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.REFNAME }}
          files: ${{ env.OUTFILE }}
